language: php
php:
- '7.0'
addons:
  apt:
    packages:
    - sshpass
install:
- composer install --no-interaction
- composer dump-autoload -o
env:
  global:
  - FREESEWING_DATA_DEPLOY_HOST=lin.freesewing.org
  - FREESEWING_DATA_DEPLOY_USER=travis
  - FREESEWING_DATA_DEPLOY_PATH=/fs/deploy/data
  - secure: ZPkRwdp55eHYmvzt7VGD8IMoqKXtCG883uiJ+8fMwT7+EY0Fhou26VUHR9XDKqGuXnyetVhY+K6mN4HrN0xGtIUUYhijm6kneVgiezd3nrRB4jESbhXXugKOEVMHZY4TIlAwnfgNNZsGfMzbbJpvyCRgxK7iiwAZS/DrFWd/7DC8U1QBqbRVWTM9ZUGzBpEN5nXBC58KuMTCSuUpsPzBgNHOaUgKsxPmgRR60at4I7/w/yd7Aa9vtIxRUu0pdszTADR+mCLV+HRdI4yyAxuItUhS8jEUYJ6RcSdHE5BohYsFMVEHl8MLDJfDgK26f7SQ2EMXPnVgp8wd9vgdX8+jPYA3K5eaqkrRXE74cwPlsGckeEIJpR4bj4vdWje+PXtBVX9ffPArTHl4s9qAAAQWKhl3KSNrCw/3dzSNx2jHNypmJKVGSOK85Z1fpukFH0HlLOXRMCul/Sz3w8cW13hbzWc+NJZKhflhfJ8zPhQWe115T7+6iVzlLK81mX9hkw5VVKB6CtgbHzN3ndxDNcbwxRZRuh9Oh1CYVuJvaS8bWP0MyunpV216awa6cZsRtLwhhnSgdhcquV41RQvstZTJupxgZir+B8xKzrR9iysMNpC7wpGgKJrDJhxJMZmqEIv75kyhIi8Tn54Ew9wPynUkyH4XWWVA9EfeLirE0fE9FkY=
  - secure: npnrsZFsaQyaxw9mUSskSGxrmG0hLUsHZyCkeLdvC0SxOB0+z/TwycVMGg+Lxs4J3TertSrAM23Q2ezC3U3bP+LT6J7WX2QwcjGHqIcyDsLHBw6PCjtchY2YI0k2GolEqLDhCM7PuUnZ2770FdT0lQPQRm15RID/bHH8oa2VRSK9vbBgBgcQcg79DzUuAnFRJOxYDXm+kNW2XyNSmNdIuBKCY9AXtGBi/oIz0oa6xH1CxVcQi5deIn6oIHhZIOStb1O74txi781g1GZ5ZmH73B6iWmM4jglE7FnLoymz1n52s+bAySe4DI7uCxcD2Zn3ajexP6O/Y3j5a0Ydv0VtD/Q+iLqJYdDCNVWyxh/BZ7vxKtPB4fHff2OsvvSt0JA/iqSiFe/pJGByT76iKr09SafbqalrpuDRgbziL4t1LGWGcSbBZkpeXPQBOBmhWmVSIyr4kWNvoEKoP/O0s/1P07XynTOmqzmeIE5kDaYX0B97Q1ZYRXWl9GDQLer4SJQUzsdvnDAkRd3ozllIuE80D1/gTZf07oYEDylb2WWCFeQ5E9sAMWyjN2vINQMh7YaTIZJqghJgD8K7ZkTPgXfqagz0IoeQsasR5WyWG0mc26+XZah33hsG5VWt0RCu2jEtSuDYqSkStj7zcmUY9/sW3TdrJ08ObCP0whwRiionchU=
  - secure: S4lg2muDSN34ILbWLQG8IXspNs2whlzLp7Z+3vUcvJfVxzC4qCPlqqnSx7CO8MHicnRTZGlzpF3rqR0mnJ+2GRA6jtlAtUaBGuW6c2i7nPxoiRy2UdOKgskkEUOVsIsPab2d1Mjw3QTdBoTtY/C2qsec4QwCulN3x80+AeTT9XNyEFxNplavcf7B14Q6hOQcAL7wH7XUcCcDfWa5fMOxFZ2EC4ewJylCewv3FEu2zIchEWqGy7lmkK+NVwaRDKyjg61gM+jMIBgVQnD+4SEaemGRj8XGwqTBpIKi/cNJtIV2W4D8TJsiJt/Hr5HX3KAWP+UrS+2tXzg8iGS8Zs3FM4gh+bJk+D5geUx0Wfu8wpPnPyBMJckw67EhIlHwBdO/AkjAlx4dz9ucPjKNYrcmoVW3mWuzvT3xHQJBkGfG5mtotydyivyDmvmmjDJaamRYG4ByCIwLpZdTrtASaHNhND9sqfcdY8jPkgX06Ky8DPhMWfSGdRxEUAD8EJrmj/eas3LflDkuJS4wjoQqxru/4hUvmhaT1No9xZHnuZ9ODxVOqMOGK9YRqTwQoEHmrcfvNPmZ6O3HCJIC9SifrrYdihocXF+IniWdBw+5ZFlytYPrOgNtw9cvJZ16mcO45q6jdBACQ3BdfreAChpSzWsBG6Y9x33mzGAjJjeQZDaCerI=
  - secure: BInoXCqZ18bM6p5hNi74P9ZQQW8jgcRZIV7Lt637BsyEw2n0trfLOvWDIgyZpNvf/4u4bUhKTv/kyQPpeNm54BK8bCGKYxuTTZTDn/QnCRmSdYPeF2Az8qbeOlcssBjlA1HI7MrXDTaHMqAtnQhBHXADgHMjfBJ0TwRihv2M3+YkyKAq50Fe+T4KW8zyCR6xPQ+usb01HppNPvhFg9W508TsWUfhmjdLALi2Cb0Th54COUxdkXiOL1DmNS3XPnuyabdrZJ9nS5y0HbKPwh9kmNKN/lLV51DVEceggQeid/YCGO5RJLopKAUD58Cv86Vp1klYUBrr2dOrk0J0/WRrMXcuqx9ucO36LH64cllzJ/OR9dui1kFXnPiH5Av+oeYsdSXWI0G0NPsmCSfiJY9Xte+tW74pRmetY615tpZuwLYVEdmWYZEcenaZmRBRBUN8pbPcSjcFfhLWMCdGVNRcoBdP82afSunrlH16vxamhMRwvLe8qhYVLVCS6QHAoJ/qOIrohnygZmn3wg2sl/ZM2H64ggjvoZAvD1Llz+rX0L1L2H4TYY7WS6h987S2qJLXxyd6BGUN0vfdw1b7zW+7EyKH7+WCQA36aL9xl7aMA/5UK35oV4OgkyJyM9gDC3293RXqabicEZXvUalRCoqVvOUlR9UQlHQFhTjukqbLh8w=
script:
- phpunit --version
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
